apiVersion: v2
name: loki
description: Loki Helm release for the k8s-homelab monitoring namespace
type: application
version: 0.1.0
dependencies:
  - name: loki
    version: 7.0.0
    repository: https://grafana.github.io/helm-charts
